/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionRouteImport } from './routes/action'
import { Route as CohomologyRouteImport } from './routes/cohomology'
import { Route as HubbleRouteImport } from './routes/hubble'
import { Route as ProjectionRouteImport } from './routes/projection'
import { Route as StarmapRouteImport } from './routes/starmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionRoute = ActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => rootRouteImport,
} as any)
const CohomologyRoute = CohomologyRouteImport.update({
  id: '/cohomology',
  path: '/cohomology',
  getParentRoute: () => rootRouteImport,
} as any)
const HubbleRoute = HubbleRouteImport.update({
  id: '/hubble',
  path: '/hubble',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionRoute = ProjectionRouteImport.update({
  id: '/projection',
  path: '/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const StarmapRoute = StarmapRouteImport.update({
  id: '/starmap',
  path: '/starmap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/cohomology': typeof CohomologyRoute
  '/hubble': typeof HubbleRoute
  '/projection': typeof ProjectionRoute
  '/starmap': typeof StarmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/cohomology': typeof CohomologyRoute
  '/hubble': typeof HubbleRoute
  '/projection': typeof ProjectionRoute
  '/starmap': typeof StarmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/cohomology': typeof CohomologyRoute
  '/hubble': typeof HubbleRoute
  '/projection': typeof ProjectionRoute
  '/starmap': typeof StarmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/action' | '/cohomology' | '/hubble' | '/projection' | '/starmap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/action' | '/cohomology' | '/hubble' | '/projection' | '/starmap'
  id:
    | '__root__'
    | '/'
    | '/action'
    | '/cohomology'
    | '/hubble'
    | '/projection'
    | '/starmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionRoute: typeof ActionRoute
  CohomologyRoute: typeof CohomologyRoute
  HubbleRoute: typeof HubbleRoute
  ProjectionRoute: typeof ProjectionRoute
  StarmapRoute: typeof StarmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action': {
      id: '/action'
      path: '/action'
      fullPath: '/action'
      preLoaderRoute: typeof ActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohomology': {
      id: '/cohomology'
      path: '/cohomology'
      fullPath: '/cohomology'
      preLoaderRoute: typeof CohomologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubble': {
      id: '/hubble'
      path: '/hubble'
      fullPath: '/hubble'
      preLoaderRoute: typeof HubbleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projection': {
      id: '/projection'
      path: '/projection'
      fullPath: '/projection'
      preLoaderRoute: typeof ProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starmap': {
      id: '/starmap'
      path: '/starmap'
      fullPath: '/starmap'
      preLoaderRoute: typeof StarmapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionRoute: ActionRoute,
  CohomologyRoute: CohomologyRoute,
  HubbleRoute: HubbleRoute,
  ProjectionRoute: ProjectionRoute,
  StarmapRoute: StarmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
